# Generated by Django 3.2 on 2023-02-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='dsffsd', unique=True, verbose_name='Жанр'),
        ),
    ]
