# Generated by Django 3.2 on 2023-02-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='genres', through='reviews.GenreTitle', to='reviews.Genre'),
        ),
    ]
