# Generated by Django 3.2 on 2023-03-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_del_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(help_text='Введите год публикации произведения', verbose_name='год публикации'),
        ),
    ]
