# Generated by Django 3.2 on 2023-02-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_title_genre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together={('name', 'slug')},
        ),
    ]
