# Generated by Django 3.2 on 2023-02-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_genre_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genre',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='unique_name_slug'),
        ),
    ]
