# Generated by Django 3.2 on 2023-02-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230228_0940'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genre',
            name='unique_name_slug',
        ),
    ]
