# Generated by Django 3.2 on 2023-02-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_db_name_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(default='описание', null=True, verbose_name='Описание'),
        ),
    ]
