# Generated by Django 3.2 on 2023-02-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_title_rating'),
        ('reviews', '0010_db_category'),
    ]

    operations = [
    ]
