# Generated by Django 3.2 on 2023-02-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_merge_0010_alter_title_rating_0010_db_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'verbose_name': 'Жанр-произведение', 'verbose_name_plural': 'Жанр-произведение'},
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
